version: '2'

services:
  fluentd-aggregator_1:
    build: ./fluentd-aggregator_1
    container_name: aggregator_1
    volumes:
      - ./fluentd-aggregator_1/config:/etc/td-agent
      - ./fluentd-aggregator_1/log:/var/log/td-agent
    networks:
      default:
        ipv4_address: 172.30.0.10
    restart: always

  fluentd-aggregator_2:
    build: ./fluentd-aggregator_2
    container_name: aggregator_2
    volumes:
      - ./fluentd-aggregator_2/config:/etc/td-agent
      - ./fluentd-aggregator_2/log:/var/log/td-agent
    networks:
      default:
        ipv4_address: 172.30.0.11
    restart: always

  fluentd-forward:
    build: ./fluentd-forwarder
    container_name: forwarder
    depends_on:
      - fluentd-aggregator_1
      - fluentd-aggregator_2
    volumes:
      - ./fluentd-forwarder/config:/etc/td-agent
      - ./fluentd-forwarder/log:/var/log/td-agent
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
